model = dict(
    type='MaskRCNN',
    backbone=dict(
        type='ResNet',
        depth=101,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained',
                      checkpoint='torchvision://resnet101')),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
    roi_head=dict(
        type='StandardRoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        bbox_head=dict(
            type='Shared2FCBBoxHead',
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=323,
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0.0, 0.0, 0.0, 0.0],
                target_stds=[0.1, 0.1, 0.2, 0.2]),
            reg_class_agnostic=False,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
        mask_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=14, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        mask_head=dict(
            type='FCNMaskHead',
            num_convs=4,
            in_channels=256,
            conv_out_channels=256,
            num_classes=323,
            loss_mask=dict(
                type='CrossEntropyLoss', use_mask=True, loss_weight=1.0))),
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=-1,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            mask_size=28,
            pos_weight=-1,
            debug=False)),
    test_cfg=dict(
        rpn=dict(
            nms_pre=1000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            score_thr=0.05,
            nms=dict(type='nms', iou_threshold=0.5),
            max_per_img=100,
            mask_thr_binary=0.5)))
dataset_type = 'CocoDataset'
data_root = 'data/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=4,
    train=dict(
        type='CocoDataset',
        ann_file='train_ann_final.json',
        img_prefix='images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
            dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
            dict(type='RandomFlip', flip_ratio=0.5),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(
                type='Collect',
                keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
        ],
        data_root='data/train/',
        classes=[
            'beetroot-steamed-without-addition-of-salt', 'bread_wholemeal',
            'jam', 'water', 'bread', 'banana', 'soft_cheese', 'ham_raw',
            'hard_cheese', 'cottage_cheese', 'coffee', 'fruit_mixed',
            'pancake', 'tea', 'salmon_smoked', 'avocado',
            'spring_onion_scallion', 'ristretto_with_caffeine', 'ham_n_s',
            'egg', 'bacon', 'chips_french_fries', 'juice_apple', 'chicken',
            'tomato', 'broccoli', 'shrimp_prawn', 'carrot', 'chickpeas',
            'french_salad_dressing', 'pasta_hornli_ch', 'sauce_cream',
            'pasta_n_s', 'tomato_sauce', 'cheese_n_s', 'pear', 'cashew_nut',
            'almonds', 'lentil_n_s', 'mixed_vegetables', 'peanut_butter',
            'apple', 'blueberries', 'cucumber', 'yogurt', 'butter',
            'mayonnaise', 'soup', 'wine_red', 'wine_white',
            'green_bean_steamed_without_addition_of_salt', 'sausage',
            'pizza_margherita_baked', 'salami_ch', 'mushroom', 'tart_n_s',
            'rice', 'white_coffee', 'sunflower_seeds', 'bell_pepper_red_raw',
            'zucchini', 'asparagus', 'tartar_sauce', 'lye_pretzel_soft',
            'cucumber_pickled_ch', 'curry_vegetarian',
            'soup_of_lentils_dahl_dhal', 'salmon',
            'salt_cake_ch_vegetables_filled', 'orange', 'pasta_noodles',
            'cream_double_cream_heavy_cream_45', 'cake_chocolate',
            'pasta_spaghetti', 'black_olives', 'parmesan', 'spaetzle',
            'salad_lambs_ear', 'salad_leaf_salad_green', 'potato',
            'white_cabbage', 'halloumi', 'beetroot_raw', 'bread_grain',
            'applesauce', 'cheese_for_raclette_ch', 'bread_white',
            'curds_natural', 'quiche', 'beef_n_s',
            'taboule_prepared_with_couscous', 'aubergine_eggplant',
            'mozzarella', 'pasta_penne', 'lasagne_vegetable_prepared',
            'mandarine', 'kiwi', 'french_beans', 'spring_roll_fried',
            'caprese_salad_tomato_mozzarella', 'leaf_spinach',
            'roll_of_half_white_or_white_flour_with_large_void',
            'omelette_with_flour_thick_crepe_plain', 'tuna', 'dark_chocolate',
            'sauce_savoury_n_s', 'raisins_dried', 'ice_tea_on_black_tea_basis',
            'kaki', 'smoothie', 'crepe_with_flour_plain', 'nuggets',
            'chili_con_carne_prepared', 'veggie_burger', 'chinese_cabbage',
            'hamburger', 'soup_pumpkin', 'sushi', 'chestnuts_ch', 'sauce_soya',
            'balsamic_salad_dressing', 'pasta_twist', 'bolognaise_sauce',
            'leek', 'fajita_bread_only', 'potato_gnocchi',
            'rice_noodles_vermicelli', 'bread_whole_wheat', 'onion', 'garlic',
            'hummus', 'pizza_with_vegetables_baked', 'beer',
            'glucose_drink_50g', 'ratatouille', 'peanut', 'cauliflower',
            'green_olives', 'bread_pita', 'pasta_wholemeal', 'sauce_pesto',
            'couscous', 'sauce', 'bread_toast', 'water_with_lemon_juice',
            'espresso', 'egg_scrambled', 'juice_orange',
            'braided_white_loaf_ch', 'emmental_cheese_ch',
            'hazelnut_chocolate_spread_nutella_ovomaltine_caotina', 'tomme_ch',
            'hazelnut', 'peach', 'figs',
            'mashed_potatoes_prepared_with_full_fat_milk_with_butter',
            'pumpkin', 'swiss_chard', 'red_cabbage_raw', 'spinach_raw',
            'chicken_curry_cream_coconut_milk_curry_spices_paste',
            'crunch_muesli', 'biscuit', 'meatloaf_ch', 'fresh_cheese_n_s',
            'honey', 'vegetable_mix_peas_and_carrots', 'parsley', 'brownie',
            'ice_cream_n_s', 'salad_dressing', 'dried_meat_n_s',
            'chicken_breast', 'mixed_salad_chopped_without_sauce', 'feta',
            'praline_n_s', 'walnut', 'potato_salad', 'kolhrabi',
            'alfa_sprouts', 'brussel_sprouts', 'gruyere_ch', 'bulgur',
            'grapes', 'chocolate_egg_small', 'cappuccino', 'crisp_bread',
            'bread_black', 'rosti_n_s', 'mango', 'muesli_dry', 'spinach',
            'fish_n_s', 'risotto', 'crisps_ch', 'pork_n_s', 'pomegranate',
            'sweet_corn', 'flakes', 'greek_salad', 'sesame_seeds', 'bouillon',
            'baked_potato', 'fennel', 'meat_n_s', 'croutons',
            'bell_pepper_red_stewed', 'nuts', 'breadcrumbs_unspiced', 'fondue',
            'sauce_mushroom', 'strawberries', 'pie_plum_baked_with_cake_dough',
            'potatoes_au_gratin_dauphinois_prepared', 'capers',
            'bread_wholemeal_toast', 'red_radish', 'fruit_tart',
            'beans_kidney', 'sauerkraut', 'mustard', 'country_fries',
            'ketchup', 'pasta_linguini_parpadelle_tagliatelle',
            'chicken_cut_into_stripes_only_meat', 'cookies',
            'sun_dried_tomatoe', 'bread_ticino_ch', 'semi_hard_cheese',
            'porridge_prepared_with_partially_skimmed_milk', 'juice',
            'chocolate_milk', 'bread_fruit', 'corn', 'dates', 'pistachio',
            'cream_cheese_n_s', 'bread_rye', 'witloof_chicory',
            'goat_cheese_soft', 'grapefruit_pomelo', 'blue_mould_cheese',
            'guacamole', 'tofu', 'cordon_bleu', 'quinoa', 'kefir_drink',
            'salad_rocket', 'pizza_with_ham_with_mushrooms_baked',
            'fruit_coulis', 'plums', 'pizza_with_ham_baked', 'pineapple',
            'seeds_n_s', 'focaccia', 'mixed_milk_beverage',
            'coleslaw_chopped_without_sauce', 'sweet_potato', 'chicken_leg',
            'croissant', 'cheesecake', 'sauce_cocktail',
            'croissant_with_chocolate_filling', 'pumpkin_seeds', 'artichoke',
            'soft_drink_with_a_taste', 'apple_pie',
            'white_bread_with_butter_eggs_and_milk', 'savoury_pastry_stick',
            'tuna_in_oil_drained', 'meat_terrine_pate', 'falafel_balls',
            'berries_n_s', 'latte_macchiato',
            'sugar_melon_galia_honeydew_cantaloupe', 'mixed_seeds_n_s',
            'oil_vinegar_salad_dressing', 'celeriac', 'chocolate_mousse',
            'lemon', 'chocolate_cookies',
            'birchermuesli_prepared_no_sugar_added', 'muffin', 'pine_nuts',
            'french_pizza_from_alsace_baked', 'chocolate_n_s',
            'grits_polenta_maize_flour', 'wine_rose', 'cola_based_drink',
            'raspberries', 'roll_with_pieces_of_chocolate', 'cake_lemon',
            'rice_wild', 'gluten_free_bread', 'pearl_onion', 'tzatziki',
            'ham_croissant_ch', 'corn_crisps', 'lentils_green_du_puy_du_berry',
            'rice_whole_grain', 'cervelat_ch',
            'aperitif_with_alcohol_n_s_aperol_spritz', 'peas', 'tiramisu',
            'apricots', 'lasagne_meat_prepared', 'brioche',
            'vegetable_au_gratin_baked', 'basil', 'butter_spread_puree_almond',
            'pie_apricot', 'rusk_wholemeal', 'pasta_in_conch_form',
            'pasta_in_butterfly_form_farfalle', 'damson_plum', 'shoots_n_s',
            'coconut', 'banana_cake', 'sauce_curry', 'watermelon_fresh',
            'white_asparagus', 'cherries', 'nectarine'
        ]),
    val=dict(
        type='CocoDataset',
        ann_file='val_ann_final.json',
        img_prefix='images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        data_root='data/val/',
        classes=[
            'beetroot-steamed-without-addition-of-salt', 'bread_wholemeal',
            'jam', 'water', 'bread', 'banana', 'soft_cheese', 'ham_raw',
            'hard_cheese', 'cottage_cheese', 'coffee', 'fruit_mixed',
            'pancake', 'tea', 'salmon_smoked', 'avocado',
            'spring_onion_scallion', 'ristretto_with_caffeine', 'ham_n_s',
            'egg', 'bacon', 'chips_french_fries', 'juice_apple', 'chicken',
            'tomato', 'broccoli', 'shrimp_prawn', 'carrot', 'chickpeas',
            'french_salad_dressing', 'pasta_hornli_ch', 'sauce_cream',
            'pasta_n_s', 'tomato_sauce', 'cheese_n_s', 'pear', 'cashew_nut',
            'almonds', 'lentil_n_s', 'mixed_vegetables', 'peanut_butter',
            'apple', 'blueberries', 'cucumber', 'yogurt', 'butter',
            'mayonnaise', 'soup', 'wine_red', 'wine_white',
            'green_bean_steamed_without_addition_of_salt', 'sausage',
            'pizza_margherita_baked', 'salami_ch', 'mushroom', 'tart_n_s',
            'rice', 'white_coffee', 'sunflower_seeds', 'bell_pepper_red_raw',
            'zucchini', 'asparagus', 'tartar_sauce', 'lye_pretzel_soft',
            'cucumber_pickled_ch', 'curry_vegetarian',
            'soup_of_lentils_dahl_dhal', 'salmon',
            'salt_cake_ch_vegetables_filled', 'orange', 'pasta_noodles',
            'cream_double_cream_heavy_cream_45', 'cake_chocolate',
            'pasta_spaghetti', 'black_olives', 'parmesan', 'spaetzle',
            'salad_lambs_ear', 'salad_leaf_salad_green', 'potato',
            'white_cabbage', 'halloumi', 'beetroot_raw', 'bread_grain',
            'applesauce', 'cheese_for_raclette_ch', 'bread_white',
            'curds_natural', 'quiche', 'beef_n_s',
            'taboule_prepared_with_couscous', 'aubergine_eggplant',
            'mozzarella', 'pasta_penne', 'lasagne_vegetable_prepared',
            'mandarine', 'kiwi', 'french_beans', 'spring_roll_fried',
            'caprese_salad_tomato_mozzarella', 'leaf_spinach',
            'roll_of_half_white_or_white_flour_with_large_void',
            'omelette_with_flour_thick_crepe_plain', 'tuna', 'dark_chocolate',
            'sauce_savoury_n_s', 'raisins_dried', 'ice_tea_on_black_tea_basis',
            'kaki', 'smoothie', 'crepe_with_flour_plain', 'nuggets',
            'chili_con_carne_prepared', 'veggie_burger', 'chinese_cabbage',
            'hamburger', 'soup_pumpkin', 'sushi', 'chestnuts_ch', 'sauce_soya',
            'balsamic_salad_dressing', 'pasta_twist', 'bolognaise_sauce',
            'leek', 'fajita_bread_only', 'potato_gnocchi',
            'rice_noodles_vermicelli', 'bread_whole_wheat', 'onion', 'garlic',
            'hummus', 'pizza_with_vegetables_baked', 'beer',
            'glucose_drink_50g', 'ratatouille', 'peanut', 'cauliflower',
            'green_olives', 'bread_pita', 'pasta_wholemeal', 'sauce_pesto',
            'couscous', 'sauce', 'bread_toast', 'water_with_lemon_juice',
            'espresso', 'egg_scrambled', 'juice_orange',
            'braided_white_loaf_ch', 'emmental_cheese_ch',
            'hazelnut_chocolate_spread_nutella_ovomaltine_caotina', 'tomme_ch',
            'hazelnut', 'peach', 'figs',
            'mashed_potatoes_prepared_with_full_fat_milk_with_butter',
            'pumpkin', 'swiss_chard', 'red_cabbage_raw', 'spinach_raw',
            'chicken_curry_cream_coconut_milk_curry_spices_paste',
            'crunch_muesli', 'biscuit', 'meatloaf_ch', 'fresh_cheese_n_s',
            'honey', 'vegetable_mix_peas_and_carrots', 'parsley', 'brownie',
            'ice_cream_n_s', 'salad_dressing', 'dried_meat_n_s',
            'chicken_breast', 'mixed_salad_chopped_without_sauce', 'feta',
            'praline_n_s', 'walnut', 'potato_salad', 'kolhrabi',
            'alfa_sprouts', 'brussel_sprouts', 'gruyere_ch', 'bulgur',
            'grapes', 'chocolate_egg_small', 'cappuccino', 'crisp_bread',
            'bread_black', 'rosti_n_s', 'mango', 'muesli_dry', 'spinach',
            'fish_n_s', 'risotto', 'crisps_ch', 'pork_n_s', 'pomegranate',
            'sweet_corn', 'flakes', 'greek_salad', 'sesame_seeds', 'bouillon',
            'baked_potato', 'fennel', 'meat_n_s', 'croutons',
            'bell_pepper_red_stewed', 'nuts', 'breadcrumbs_unspiced', 'fondue',
            'sauce_mushroom', 'strawberries', 'pie_plum_baked_with_cake_dough',
            'potatoes_au_gratin_dauphinois_prepared', 'capers',
            'bread_wholemeal_toast', 'red_radish', 'fruit_tart',
            'beans_kidney', 'sauerkraut', 'mustard', 'country_fries',
            'ketchup', 'pasta_linguini_parpadelle_tagliatelle',
            'chicken_cut_into_stripes_only_meat', 'cookies',
            'sun_dried_tomatoe', 'bread_ticino_ch', 'semi_hard_cheese',
            'porridge_prepared_with_partially_skimmed_milk', 'juice',
            'chocolate_milk', 'bread_fruit', 'corn', 'dates', 'pistachio',
            'cream_cheese_n_s', 'bread_rye', 'witloof_chicory',
            'goat_cheese_soft', 'grapefruit_pomelo', 'blue_mould_cheese',
            'guacamole', 'tofu', 'cordon_bleu', 'quinoa', 'kefir_drink',
            'salad_rocket', 'pizza_with_ham_with_mushrooms_baked',
            'fruit_coulis', 'plums', 'pizza_with_ham_baked', 'pineapple',
            'seeds_n_s', 'focaccia', 'mixed_milk_beverage',
            'coleslaw_chopped_without_sauce', 'sweet_potato', 'chicken_leg',
            'croissant', 'cheesecake', 'sauce_cocktail',
            'croissant_with_chocolate_filling', 'pumpkin_seeds', 'artichoke',
            'soft_drink_with_a_taste', 'apple_pie',
            'white_bread_with_butter_eggs_and_milk', 'savoury_pastry_stick',
            'tuna_in_oil_drained', 'meat_terrine_pate', 'falafel_balls',
            'berries_n_s', 'latte_macchiato',
            'sugar_melon_galia_honeydew_cantaloupe', 'mixed_seeds_n_s',
            'oil_vinegar_salad_dressing', 'celeriac', 'chocolate_mousse',
            'lemon', 'chocolate_cookies',
            'birchermuesli_prepared_no_sugar_added', 'muffin', 'pine_nuts',
            'french_pizza_from_alsace_baked', 'chocolate_n_s',
            'grits_polenta_maize_flour', 'wine_rose', 'cola_based_drink',
            'raspberries', 'roll_with_pieces_of_chocolate', 'cake_lemon',
            'rice_wild', 'gluten_free_bread', 'pearl_onion', 'tzatziki',
            'ham_croissant_ch', 'corn_crisps', 'lentils_green_du_puy_du_berry',
            'rice_whole_grain', 'cervelat_ch',
            'aperitif_with_alcohol_n_s_aperol_spritz', 'peas', 'tiramisu',
            'apricots', 'lasagne_meat_prepared', 'brioche',
            'vegetable_au_gratin_baked', 'basil', 'butter_spread_puree_almond',
            'pie_apricot', 'rusk_wholemeal', 'pasta_in_conch_form',
            'pasta_in_butterfly_form_farfalle', 'damson_plum', 'shoots_n_s',
            'coconut', 'banana_cake', 'sauce_curry', 'watermelon_fresh',
            'white_asparagus', 'cherries', 'nectarine'
        ]),
    test=dict(
        type='CocoDataset',
        ann_file='val_ann_final.json',
        img_prefix='images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        data_root='',
        classes=[
            'beetroot-steamed-without-addition-of-salt', 'bread_wholemeal',
            'jam', 'water', 'bread', 'banana', 'soft_cheese', 'ham_raw',
            'hard_cheese', 'cottage_cheese', 'coffee', 'fruit_mixed',
            'pancake', 'tea', 'salmon_smoked', 'avocado',
            'spring_onion_scallion', 'ristretto_with_caffeine', 'ham_n_s',
            'egg', 'bacon', 'chips_french_fries', 'juice_apple', 'chicken',
            'tomato', 'broccoli', 'shrimp_prawn', 'carrot', 'chickpeas',
            'french_salad_dressing', 'pasta_hornli_ch', 'sauce_cream',
            'pasta_n_s', 'tomato_sauce', 'cheese_n_s', 'pear', 'cashew_nut',
            'almonds', 'lentil_n_s', 'mixed_vegetables', 'peanut_butter',
            'apple', 'blueberries', 'cucumber', 'yogurt', 'butter',
            'mayonnaise', 'soup', 'wine_red', 'wine_white',
            'green_bean_steamed_without_addition_of_salt', 'sausage',
            'pizza_margherita_baked', 'salami_ch', 'mushroom', 'tart_n_s',
            'rice', 'white_coffee', 'sunflower_seeds', 'bell_pepper_red_raw',
            'zucchini', 'asparagus', 'tartar_sauce', 'lye_pretzel_soft',
            'cucumber_pickled_ch', 'curry_vegetarian',
            'soup_of_lentils_dahl_dhal', 'salmon',
            'salt_cake_ch_vegetables_filled', 'orange', 'pasta_noodles',
            'cream_double_cream_heavy_cream_45', 'cake_chocolate',
            'pasta_spaghetti', 'black_olives', 'parmesan', 'spaetzle',
            'salad_lambs_ear', 'salad_leaf_salad_green', 'potato',
            'white_cabbage', 'halloumi', 'beetroot_raw', 'bread_grain',
            'applesauce', 'cheese_for_raclette_ch', 'bread_white',
            'curds_natural', 'quiche', 'beef_n_s',
            'taboule_prepared_with_couscous', 'aubergine_eggplant',
            'mozzarella', 'pasta_penne', 'lasagne_vegetable_prepared',
            'mandarine', 'kiwi', 'french_beans', 'spring_roll_fried',
            'caprese_salad_tomato_mozzarella', 'leaf_spinach',
            'roll_of_half_white_or_white_flour_with_large_void',
            'omelette_with_flour_thick_crepe_plain', 'tuna', 'dark_chocolate',
            'sauce_savoury_n_s', 'raisins_dried', 'ice_tea_on_black_tea_basis',
            'kaki', 'smoothie', 'crepe_with_flour_plain', 'nuggets',
            'chili_con_carne_prepared', 'veggie_burger', 'chinese_cabbage',
            'hamburger', 'soup_pumpkin', 'sushi', 'chestnuts_ch', 'sauce_soya',
            'balsamic_salad_dressing', 'pasta_twist', 'bolognaise_sauce',
            'leek', 'fajita_bread_only', 'potato_gnocchi',
            'rice_noodles_vermicelli', 'bread_whole_wheat', 'onion', 'garlic',
            'hummus', 'pizza_with_vegetables_baked', 'beer',
            'glucose_drink_50g', 'ratatouille', 'peanut', 'cauliflower',
            'green_olives', 'bread_pita', 'pasta_wholemeal', 'sauce_pesto',
            'couscous', 'sauce', 'bread_toast', 'water_with_lemon_juice',
            'espresso', 'egg_scrambled', 'juice_orange',
            'braided_white_loaf_ch', 'emmental_cheese_ch',
            'hazelnut_chocolate_spread_nutella_ovomaltine_caotina', 'tomme_ch',
            'hazelnut', 'peach', 'figs',
            'mashed_potatoes_prepared_with_full_fat_milk_with_butter',
            'pumpkin', 'swiss_chard', 'red_cabbage_raw', 'spinach_raw',
            'chicken_curry_cream_coconut_milk_curry_spices_paste',
            'crunch_muesli', 'biscuit', 'meatloaf_ch', 'fresh_cheese_n_s',
            'honey', 'vegetable_mix_peas_and_carrots', 'parsley', 'brownie',
            'ice_cream_n_s', 'salad_dressing', 'dried_meat_n_s',
            'chicken_breast', 'mixed_salad_chopped_without_sauce', 'feta',
            'praline_n_s', 'walnut', 'potato_salad', 'kolhrabi',
            'alfa_sprouts', 'brussel_sprouts', 'gruyere_ch', 'bulgur',
            'grapes', 'chocolate_egg_small', 'cappuccino', 'crisp_bread',
            'bread_black', 'rosti_n_s', 'mango', 'muesli_dry', 'spinach',
            'fish_n_s', 'risotto', 'crisps_ch', 'pork_n_s', 'pomegranate',
            'sweet_corn', 'flakes', 'greek_salad', 'sesame_seeds', 'bouillon',
            'baked_potato', 'fennel', 'meat_n_s', 'croutons',
            'bell_pepper_red_stewed', 'nuts', 'breadcrumbs_unspiced', 'fondue',
            'sauce_mushroom', 'strawberries', 'pie_plum_baked_with_cake_dough',
            'potatoes_au_gratin_dauphinois_prepared', 'capers',
            'bread_wholemeal_toast', 'red_radish', 'fruit_tart',
            'beans_kidney', 'sauerkraut', 'mustard', 'country_fries',
            'ketchup', 'pasta_linguini_parpadelle_tagliatelle',
            'chicken_cut_into_stripes_only_meat', 'cookies',
            'sun_dried_tomatoe', 'bread_ticino_ch', 'semi_hard_cheese',
            'porridge_prepared_with_partially_skimmed_milk', 'juice',
            'chocolate_milk', 'bread_fruit', 'corn', 'dates', 'pistachio',
            'cream_cheese_n_s', 'bread_rye', 'witloof_chicory',
            'goat_cheese_soft', 'grapefruit_pomelo', 'blue_mould_cheese',
            'guacamole', 'tofu', 'cordon_bleu', 'quinoa', 'kefir_drink',
            'salad_rocket', 'pizza_with_ham_with_mushrooms_baked',
            'fruit_coulis', 'plums', 'pizza_with_ham_baked', 'pineapple',
            'seeds_n_s', 'focaccia', 'mixed_milk_beverage',
            'coleslaw_chopped_without_sauce', 'sweet_potato', 'chicken_leg',
            'croissant', 'cheesecake', 'sauce_cocktail',
            'croissant_with_chocolate_filling', 'pumpkin_seeds', 'artichoke',
            'soft_drink_with_a_taste', 'apple_pie',
            'white_bread_with_butter_eggs_and_milk', 'savoury_pastry_stick',
            'tuna_in_oil_drained', 'meat_terrine_pate', 'falafel_balls',
            'berries_n_s', 'latte_macchiato',
            'sugar_melon_galia_honeydew_cantaloupe', 'mixed_seeds_n_s',
            'oil_vinegar_salad_dressing', 'celeriac', 'chocolate_mousse',
            'lemon', 'chocolate_cookies',
            'birchermuesli_prepared_no_sugar_added', 'muffin', 'pine_nuts',
            'french_pizza_from_alsace_baked', 'chocolate_n_s',
            'grits_polenta_maize_flour', 'wine_rose', 'cola_based_drink',
            'raspberries', 'roll_with_pieces_of_chocolate', 'cake_lemon',
            'rice_wild', 'gluten_free_bread', 'pearl_onion', 'tzatziki',
            'ham_croissant_ch', 'corn_crisps', 'lentils_green_du_puy_du_berry',
            'rice_whole_grain', 'cervelat_ch',
            'aperitif_with_alcohol_n_s_aperol_spritz', 'peas', 'tiramisu',
            'apricots', 'lasagne_meat_prepared', 'brioche',
            'vegetable_au_gratin_baked', 'basil', 'butter_spread_puree_almond',
            'pie_apricot', 'rusk_wholemeal', 'pasta_in_conch_form',
            'pasta_in_butterfly_form_farfalle', 'damson_plum', 'shoots_n_s',
            'coconut', 'banana_cake', 'sauce_curry', 'watermelon_fresh',
            'white_asparagus', 'cherries', 'nectarine'
        ]))
evaluation = dict(metric=['bbox', 'segm'], interval=10)
optimizer = dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[8, 11])
runner = dict(type='EpochBasedRunner', max_epochs=50)
checkpoint_config = dict(interval=10)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
custom_hooks = [dict(type='NumClassCheckHook')]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
opencv_num_threads = 0
mp_start_method = 'fork'
classes = [
    'beetroot-steamed-without-addition-of-salt', 'bread_wholemeal', 'jam',
    'water', 'bread', 'banana', 'soft_cheese', 'ham_raw', 'hard_cheese',
    'cottage_cheese', 'coffee', 'fruit_mixed', 'pancake', 'tea',
    'salmon_smoked', 'avocado', 'spring_onion_scallion',
    'ristretto_with_caffeine', 'ham_n_s', 'egg', 'bacon', 'chips_french_fries',
    'juice_apple', 'chicken', 'tomato', 'broccoli', 'shrimp_prawn', 'carrot',
    'chickpeas', 'french_salad_dressing', 'pasta_hornli_ch', 'sauce_cream',
    'pasta_n_s', 'tomato_sauce', 'cheese_n_s', 'pear', 'cashew_nut', 'almonds',
    'lentil_n_s', 'mixed_vegetables', 'peanut_butter', 'apple', 'blueberries',
    'cucumber', 'yogurt', 'butter', 'mayonnaise', 'soup', 'wine_red',
    'wine_white', 'green_bean_steamed_without_addition_of_salt', 'sausage',
    'pizza_margherita_baked', 'salami_ch', 'mushroom', 'tart_n_s', 'rice',
    'white_coffee', 'sunflower_seeds', 'bell_pepper_red_raw', 'zucchini',
    'asparagus', 'tartar_sauce', 'lye_pretzel_soft', 'cucumber_pickled_ch',
    'curry_vegetarian', 'soup_of_lentils_dahl_dhal', 'salmon',
    'salt_cake_ch_vegetables_filled', 'orange', 'pasta_noodles',
    'cream_double_cream_heavy_cream_45', 'cake_chocolate', 'pasta_spaghetti',
    'black_olives', 'parmesan', 'spaetzle', 'salad_lambs_ear',
    'salad_leaf_salad_green', 'potato', 'white_cabbage', 'halloumi',
    'beetroot_raw', 'bread_grain', 'applesauce', 'cheese_for_raclette_ch',
    'bread_white', 'curds_natural', 'quiche', 'beef_n_s',
    'taboule_prepared_with_couscous', 'aubergine_eggplant', 'mozzarella',
    'pasta_penne', 'lasagne_vegetable_prepared', 'mandarine', 'kiwi',
    'french_beans', 'spring_roll_fried', 'caprese_salad_tomato_mozzarella',
    'leaf_spinach', 'roll_of_half_white_or_white_flour_with_large_void',
    'omelette_with_flour_thick_crepe_plain', 'tuna', 'dark_chocolate',
    'sauce_savoury_n_s', 'raisins_dried', 'ice_tea_on_black_tea_basis', 'kaki',
    'smoothie', 'crepe_with_flour_plain', 'nuggets',
    'chili_con_carne_prepared', 'veggie_burger', 'chinese_cabbage',
    'hamburger', 'soup_pumpkin', 'sushi', 'chestnuts_ch', 'sauce_soya',
    'balsamic_salad_dressing', 'pasta_twist', 'bolognaise_sauce', 'leek',
    'fajita_bread_only', 'potato_gnocchi', 'rice_noodles_vermicelli',
    'bread_whole_wheat', 'onion', 'garlic', 'hummus',
    'pizza_with_vegetables_baked', 'beer', 'glucose_drink_50g', 'ratatouille',
    'peanut', 'cauliflower', 'green_olives', 'bread_pita', 'pasta_wholemeal',
    'sauce_pesto', 'couscous', 'sauce', 'bread_toast',
    'water_with_lemon_juice', 'espresso', 'egg_scrambled', 'juice_orange',
    'braided_white_loaf_ch', 'emmental_cheese_ch',
    'hazelnut_chocolate_spread_nutella_ovomaltine_caotina', 'tomme_ch',
    'hazelnut', 'peach', 'figs',
    'mashed_potatoes_prepared_with_full_fat_milk_with_butter', 'pumpkin',
    'swiss_chard', 'red_cabbage_raw', 'spinach_raw',
    'chicken_curry_cream_coconut_milk_curry_spices_paste', 'crunch_muesli',
    'biscuit', 'meatloaf_ch', 'fresh_cheese_n_s', 'honey',
    'vegetable_mix_peas_and_carrots', 'parsley', 'brownie', 'ice_cream_n_s',
    'salad_dressing', 'dried_meat_n_s', 'chicken_breast',
    'mixed_salad_chopped_without_sauce', 'feta', 'praline_n_s', 'walnut',
    'potato_salad', 'kolhrabi', 'alfa_sprouts', 'brussel_sprouts',
    'gruyere_ch', 'bulgur', 'grapes', 'chocolate_egg_small', 'cappuccino',
    'crisp_bread', 'bread_black', 'rosti_n_s', 'mango', 'muesli_dry',
    'spinach', 'fish_n_s', 'risotto', 'crisps_ch', 'pork_n_s', 'pomegranate',
    'sweet_corn', 'flakes', 'greek_salad', 'sesame_seeds', 'bouillon',
    'baked_potato', 'fennel', 'meat_n_s', 'croutons', 'bell_pepper_red_stewed',
    'nuts', 'breadcrumbs_unspiced', 'fondue', 'sauce_mushroom', 'strawberries',
    'pie_plum_baked_with_cake_dough', 'potatoes_au_gratin_dauphinois_prepared',
    'capers', 'bread_wholemeal_toast', 'red_radish', 'fruit_tart',
    'beans_kidney', 'sauerkraut', 'mustard', 'country_fries', 'ketchup',
    'pasta_linguini_parpadelle_tagliatelle',
    'chicken_cut_into_stripes_only_meat', 'cookies', 'sun_dried_tomatoe',
    'bread_ticino_ch', 'semi_hard_cheese',
    'porridge_prepared_with_partially_skimmed_milk', 'juice', 'chocolate_milk',
    'bread_fruit', 'corn', 'dates', 'pistachio', 'cream_cheese_n_s',
    'bread_rye', 'witloof_chicory', 'goat_cheese_soft', 'grapefruit_pomelo',
    'blue_mould_cheese', 'guacamole', 'tofu', 'cordon_bleu', 'quinoa',
    'kefir_drink', 'salad_rocket', 'pizza_with_ham_with_mushrooms_baked',
    'fruit_coulis', 'plums', 'pizza_with_ham_baked', 'pineapple', 'seeds_n_s',
    'focaccia', 'mixed_milk_beverage', 'coleslaw_chopped_without_sauce',
    'sweet_potato', 'chicken_leg', 'croissant', 'cheesecake', 'sauce_cocktail',
    'croissant_with_chocolate_filling', 'pumpkin_seeds', 'artichoke',
    'soft_drink_with_a_taste', 'apple_pie',
    'white_bread_with_butter_eggs_and_milk', 'savoury_pastry_stick',
    'tuna_in_oil_drained', 'meat_terrine_pate', 'falafel_balls', 'berries_n_s',
    'latte_macchiato', 'sugar_melon_galia_honeydew_cantaloupe',
    'mixed_seeds_n_s', 'oil_vinegar_salad_dressing', 'celeriac',
    'chocolate_mousse', 'lemon', 'chocolate_cookies',
    'birchermuesli_prepared_no_sugar_added', 'muffin', 'pine_nuts',
    'french_pizza_from_alsace_baked', 'chocolate_n_s',
    'grits_polenta_maize_flour', 'wine_rose', 'cola_based_drink',
    'raspberries', 'roll_with_pieces_of_chocolate', 'cake_lemon', 'rice_wild',
    'gluten_free_bread', 'pearl_onion', 'tzatziki', 'ham_croissant_ch',
    'corn_crisps', 'lentils_green_du_puy_du_berry', 'rice_whole_grain',
    'cervelat_ch', 'aperitif_with_alcohol_n_s_aperol_spritz', 'peas',
    'tiramisu', 'apricots', 'lasagne_meat_prepared', 'brioche',
    'vegetable_au_gratin_baked', 'basil', 'butter_spread_puree_almond',
    'pie_apricot', 'rusk_wholemeal', 'pasta_in_conch_form',
    'pasta_in_butterfly_form_farfalle', 'damson_plum', 'shoots_n_s', 'coconut',
    'banana_cake', 'sauce_curry', 'watermelon_fresh', 'white_asparagus',
    'cherries', 'nectarine'
]
work_dir = 'results_mask'
seed = 0
gpu_ids = range(0, 6)
auto_resume = False
